### ISSUE TITLE
As Pho I want to enable the Display view for a local group

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#69] opened 2017-12-06 11:32 UTC
PR: 
* https://github.com/buzzn/core/pull/1322
* https://github.com/buzzn/admin-app/pull/259
* https://github.com/buzzn/display-app/pull/75
* https://github.com/buzzn/module-bubbles/commits/master
---
**Story:**
As Pho I want to enable the Display view for a local group so my customers can see their group energy online.

---
**XD**
- [x] prepare friendly message screen if display link gets opened without enabled display view. Message is: "Deine Energiegruppe ist aktuell nicht für diese Ansicht freigeschaltet. Bitte wende Dich an Deinen Stromgeber:" -> below Picture and name of the groupowner.  

InVision Mockup: https://projects.invisionapp.com/d/main#/console/10620153/268819426/preview

---

**Definition of done**
- [x] the display view can be enabled and disabled in the groups-setings page
- [x] if enabled: generate link with group slug and display the link below the toggle; OnClick on the link opens the display view of that group in a new window
- [x] if enabled, display view is publicly accessable without login
- [x] if disabled: don´t show the link. If link is opened by someone, show friendly message that the display view is disabled at the moment
- [x] all slugs are readable and allow Umlaut in groupnames ("Schäfflerstraße -> slug schaefflerstrasse)
- [x] no dropdown to choose the group

excluded:

- daily line charts in Display view #74 
- show correct values for current power consumption, total power consumption and production and autarkie 
- all data is rendered with good performance and the groups feels vivid (boosting) #77 
- show sources and powertaker in #80

---
**Technical details**

_Backend_

- [x] API: endpoint to store the value of the setting as `show_display_app`
- [x] API: include link to display app as `display_app_url` in the group information
- [x] slug: transscribe umlaut to -e and ß to ss.
- [x] send 403 on all_endpoints API request when display app isn't enabled

_Frontend_

- [x] add "display app" toggle to frontend and make it editable
- [x] show/hide URL depending on the setting
- [x] on every request, check if we get 403 and show the message "unauthorized"
- [x] remove dropdown to choose the group

**Comment by dottorer** [comment] 2017-12-08 16:19
@evaklopp @phillipoertel In an attempt to make our stories smaller and more crisp, I cut out two bits in to separate stories. We can re-estimate this story now and see when we get the other 2 in the sprint.

**Comment by phillipoertel** [comment] 2017-12-11 15:23
@dottorer @evaklopp I just realized that the slugs will be easy to guess if you know buzzn client's names. So how bad would it be if someone unrelated to a localpool could guess it and look at their display app? 
To prevent guessing, we could either add a few random characters to the display app url, or use a non-guessable, random identifier.

**Comment by dottorer** [comment] 2017-12-11 15:38
@phillipoertel We had long discussions in the past about the exposure bit of all this. Good point.

In the end, we said that we are not exposing individual power data or names of any group members unless the opt in themselves. We only show aggregates and group totals as well as 'Allgemeinstrom'. This should be fine to get at by anyone if they guess the slug. So I would leave it as is.

For reference, the prior security discussions are here: https://buzzn-team.atlassian.net/wiki/spaces/DEV/pages/148595/Design+Security+Model+v2

**Comment by phillipoertel** [comment] 2017-12-11 16:12
Thanks for the clarification.

**Comment by evaklopp** [comment] 2017-12-12 10:10
@eharit I added a new friendly message.

**Comment by dottorer** [comment] 2017-12-14 07:30
@evaklopp We need to handle the case where someone enters a URL for a non-existing group such as "display.buzzn.io/nogroup". There we cannot say 'Your group isn't enabled' but need to handle a 404. Maybe we can define a clean page for that, too. The difference is that in the case stated in the DoD the group existst, but has not been enabled, in this case no such group exists.

As this story is in flight, we should track this as 'excluded' and add a new story when it becomes priority.

@eharit The InVision mockup above says I am not a collaborator on the project so cannot see it. All other mockups work for me. Is this in a different project?

**Comment by dottorer** [comment] 2017-12-14 08:14
@evaklopp After some clarifications with @mkristian I think we should clean up the sub-story break down as follows:
1. #69 (this tic) is only about enabling /disabling
2. NEW tic for showing the correct bubbles of all registers to display current **power** consumption
3. NEW tic for showing the correct arcs and circle for current **power** production
4. #77 clarify that is is only about boosting i.e. having a virtual group aggregate in Discovergy
5. NEW tic for showing correct current **total power** consumption of entire group
6. NEW tic for showing **total daily energy** consumption and production for group
7. Cleanup #74 to focus only on line charts to render daily history of power cons/prod
8. NEW tic for calculating autarchy based on daily energy consumption vs production.

All of these have their own idiosyncrasies and we need to crisply work out based on which endpoint we can optimally derive the data for any of them.  Then we can build out a reliable and fast display view.

**Comment by phillipoertel** [comment] 2017-12-15 09:32
@mkristian @mkristian @dottorer @evaklopp in the tech planning we decided to use ä and ß for the slugs (they work and we though they would be valid). But I couldn't find any documentation/RFC  which states that non-ascii chars are actually allowed unencoded in the url. Since the slugs will be long-lived, we should review if we really want to rely on that before making them public. Code-wise, it's a tiny change to convert äöüß to ascii.

**Comment by phillipoertel** [comment] 2017-12-15 16:26
I researched some more about URLs. It think umlauts etc. are allowed unencoded in the path-part of an URL (then it's a so-called IRI, defined by RFC 3987). But all major publications (German, Spanish, Russianm, Chinese) I looked at encode or avoid them.

**Comment by evaklopp** [comment] 2017-12-18 21:35
@phillipoertel two things:
- slugs need to be readable, that means that I don´t get a cryptic letter combination if there is an Umlaut or ß
- german users are used to write and read ä as ae and ß as ss 

At the moment I don´t know where this strong need for ä/ü/ö/ in URLs comes from, you mentioned you decided it in the tech planning? As it is no special need for PhO or any other user (as far as I know?), I would focus on readablility, which is totally fine with the common use of ae/ue/oe and ss.

**Comment by mkristian** [comment] 2017-12-19 07:12
the current implementation transcribes the german diaeresis and ß, all other non-ascii characters as ë, î, ñ, µ, etc are still as is and are not transcribed. 

@evaklopp shall they be deleted from slug or can they stay as they are or shall they be transcribed ?

**Comment by phillipoertel** [comment] 2017-12-19 09:43
@mkristian FYI the low-level slug generation gem [babosa](https://github.com/norman/babosa) looks very promising. I think it would handle all problems that can happen when one wants to use a regular text as part of the URL.

**Comment by mkristian** [comment] 2017-12-19 09:45
@phillipoertel just closed the PR and going to give this to @evaklopp . so I am not going to start over again. reaching middle of the week without and still working on last weeks stories :(

**Comment by mkristian** [comment] 2017-12-19 09:52
@phillipoertel we can use the gem the next time we touch the slugs. I am all for low-level modular gems ;)

**Comment by mkristian** [comment] 2017-12-19 12:17
@evaklopp this is already deployed on staging. but it depends on the #62. only then you will be able to see the display app when the switch is on.

everything is wired up nicely, go to a localgroup in the admin-app, set the switch showDisplayApp to on, then the link will appear, follow it. disable the app and you will see the 'sorry'-page after a short time or on new load.

**Comment by mkristian** [comment] 2017-12-20 14:42
@evaklopp this is working now but only the People Power Group does show bubbles but all other obey the switch from the admin-app

**Comment by evaklopp** [comment] 2017-12-20 15:39
@mkristian Why do the other groups obey the switch? 

As soon as I click on a enabled-group-link, the new tab opens correctly but for a tiny bit of a second I see the "your group is not enabled"-screen. Can we avoid this? If not, we need a "preloader" or sth like that (own story)

**Comment by evaklopp** [comment] 2017-12-20 15:45
@mkristian sometimes if I disable a group, the link stays: 

![bildschirmfoto 2017-12-20 um 16 42 08](https://user-images.githubusercontent.com/22292464/34215177-dcd2648c-e5a4-11e7-9d2b-c87661643253.png)

Just found out that this happens reproducable when you enabled the switch, click on the link to open the display view, go back to buzzn.com (admin) and disable the switch. Than the link stays. If you click the switch again and again, it works fine.

**Comment by dottorer** [comment] 2017-12-21 07:56
@scsirdx I think the items mentioned by @evaklopp are likely front end things to check into. 

Another small suggestion: Could we make the slug name an underlined link, and move the icon to open in another window over a few pixels to leave a bit of space?

**Comment by scsirdx** [comment] 2017-12-21 23:05
This bug (with partly working switch) is much deeper than expected. I temporary hacked it, so it's a technical debt now.

**Comment by evaklopp** [comment] 2017-12-22 09:38
@scsirdx @dottorer All works very fine, despite of the discovered bug. Shall we open up a new story for it to tackle it down?

**Comment by mkristian** [comment] 2017-12-22 09:48
did not see all these comments before. @evaklopp what discovergy bug are you referring in you last comment ?

**Comment by evaklopp** [comment] 2017-12-22 14:38
@scsirdx the xd-team provided a different friendly message last week which is linked in the inVision-Link you see in the story-description. The Text is: "Deine Energiegruppe ist aktuell nicht für diese Ansicht freigeschaltet. Bitte wende Dich an Deinen Stromgeber:" and below that a picture of the groupowner (default if no picture is availiabel)

**Comment by evaklopp** [comment] 2017-12-22 14:40
@mkristian I talked abut the bug Pavel discovered (NOT discovergy! ;-) ) yesterday and he told us this morning in the standup about the switch...

**Comment by evaklopp** [comment] 2018-01-14 16:06
@dottorer @scsirdx why is this reopened?

**Comment by evaklopp** [comment] 2018-01-15 09:26
closing

**Closed by evaklopp** 2018-01-15 09:26 UTC
Labels: DISPLAY LIVE, User Story, size: 5
